import pandas as pd

movies = [
    {
        "id": 1,
        "title": "Inception",
        "genre": "Sci-Fi, Action, Thriller",
        "director": "Christopher Nolan",
        "cast": "Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page",
        "year": 2010,
        "description": "A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.",
        "rating": 8.8,
        "popularity": 95,
        "is_trending": 1
    },
    {
        "id": 2,
        "title": "The Dark Knight",
        "genre": "Action, Crime, Drama",
        "director": "Christopher Nolan",
        "cast": "Christian Bale, Heath Ledger, Aaron Eckhart",
        "year": 2008,
        "description": "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests to fight injustice.",
        "rating": 9.0,
        "popularity": 98,
        "is_trending": 0
    },
    {
        "id": 3,
        "title": "Interstellar",
        "genre": "Sci-Fi, Adventure, Drama",
        "director": "Christopher Nolan",
        "cast": "Matthew McConaughey, Anne Hathaway, Jessica Chastain",
        "year": 2014,
        "description": "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
        "rating": 8.7,
        "popularity": 94,
        "is_trending": 1
    },
    {
        "id": 4,
        "title": "The Matrix",
        "genre": "Sci-Fi, Action",
        "director": "Lana Wachowski, Lilly Wachowski",
        "cast": "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss",
        "year": 1999,
        "description": "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
        "rating": 8.7,
        "popularity": 92,
        "is_trending": 0
    },
    {
        "id": 5,
        "title": "Blade Runner 2049",
        "genre": "Sci-Fi, Thriller, Drama",
        "director": "Denis Villeneuve",
        "cast": "Ryan Gosling, Harrison Ford, Ana de Armas",
        "year": 2017,
        "description": "A new blade runner, LAPD Officer K, unearths a long-buried secret that has the potential to plunge what is left of society into chaos.",
        "rating": 8.0,
        "popularity": 88,
        "is_trending": 1
    },
    {
        "id": 6,
        "title": "Arrival",
        "genre": "Sci-Fi, Drama, Mystery",
        "director": "Denis Villeneuve",
        "cast": "Amy Adams, Jeremy Renner, Forest Whitaker",
        "year": 2016,
        "description": "A linguist works with the military to communicate with alien spacecraft that have landed on Earth.",
        "rating": 7.9,
        "popularity": 85,
        "is_trending": 0
    },
    {
        "id": 7,
        "title": "Dune",
        "genre": "Sci-Fi, Adventure, Drama",
        "director": "Denis Villeneuve",
        "cast": "Timothee Chalamet, Rebecca Ferguson, Zendaya",
        "year": 2021,
        "description": "A noble family becomes embroiled in a war for control over the galaxy's most valuable asset while its heir is haunted by visions of a dark future.",
        "rating": 8.0,
        "popularity": 91,
        "is_trending": 1
    },
    {
        "id": 8,
        "title": "Pulp Fiction",
        "genre": "Crime, Drama",
        "director": "Quentin Tarantino",
        "cast": "John Travolta, Uma Thurman, Samuel L. Jackson",
        "year": 1994,
        "description": "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
        "rating": 8.9,
        "popularity": 93,
        "is_trending": 0
    },
    {
        "id": 9,
        "title": "Inglourious Basterds",
        "genre": "Action, Drama, War",
        "director": "Quentin Tarantino",
        "cast": "Brad Pitt, Diane Kruger, Christoph Waltz",
        "year": 2009,
        "description": "In Nazi-occupied France during World War II, a plan to assassinate Adolf Hitler by a group of Jewish U.S. soldiers coincides with a theatre owner's vengeful plans.",
        "rating": 8.3,
        "popularity": 89,
        "is_trending": 0
    },
    {
        "id": 10,
        "title": "Django Unchained",
        "genre": "Drama, Western",
        "director": "Quentin Tarantino",
        "cast": "Jamie Foxx, Christoph Waltz, Leonardo DiCaprio",
        "year": 2012,
        "description": "With the help of a German bounty-hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.",
        "rating": 8.5,
        "popularity": 92,
        "is_trending": 1
    },
    {
        "id": 11,
        "title": "The Shawshank Redemption",
        "genre": "Drama",
        "director": "Frank Darabont",
        "cast": "Tim Robbins, Morgan Freeman, Bob Gunton",
        "year": 1994,
        "description": "Over the course of several years, two convicts form a friendship, seeking consolation and, eventually, redemption through basic compassion.",
        "rating": 9.3,
        "popularity": 97,
        "is_trending": 0
    },
    {
        "id": 12,
        "title": "The Godfather",
        "genre": "Crime, Drama",
        "director": "Francis Ford Coppola",
        "cast": "Marlon Brando, Al Pacino, James Caan",
        "year": 1972,
        "description": "The aging patriarch of an organized crime dynasty in postwar New York City transfers control of his clandestine empire to his reluctant youngest son.",
        "rating": 9.2,
        "popularity": 96,
        "is_trending": 0
    },
    {
        "id": 13,
        "title": "Fight Club",
        "genre": "Drama, Thriller",
        "director": "David Fincher",
        "cast": "Brad Pitt, Edward Norton, Meat Loaf",
        "year": 1999,
        "description": "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.",
        "rating": 8.8,
        "popularity": 94,
        "is_trending": 0
    },
    {
        "id": 14,
        "title": "Se7en",
        "genre": "Crime, Drama, Mystery",
        "director": "David Fincher",
        "cast": "Morgan Freeman, Brad Pitt, Kevin Spacey",
        "year": 1995,
        "description": "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.",
        "rating": 8.6,
        "popularity": 91,
        "is_trending": 0
    },
    {
        "id": 15,
        "title": "Shutter Island",
        "genre": "Mystery, Thriller",
        "director": "Martin Scorsese",
        "cast": "Leonardo DiCaprio, Mark Ruffalo, Ben Kingsley",
        "year": 2010,
        "description": "In 1954, a U.S. Marshal investigates the disappearance of a murderer who escaped from a hospital for the criminally insane.",
        "rating": 8.2,
        "popularity": 90,
        "is_trending": 1
    },
    {
        "id": 16,
        "title": "The Departed",
        "genre": "Crime, Drama, Thriller",
        "director": "Martin Scorsese",
        "cast": "Leonardo DiCaprio, Matt Damon, Jack Nicholson",
        "year": 2006,
        "description": "An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in Boston.",
        "rating": 8.5,
        "popularity": 91,
        "is_trending": 0
    },
    {
        "id": 17,
        "title": "The Wolf of Wall Street",
        "genre": "Biography, Comedy, Crime",
        "director": "Martin Scorsese",
        "cast": "Leonardo DiCaprio, Jonah Hill, Margot Robbie",
        "year": 2013,
        "description": "Based on the true story of Jordan Belfort, from his rise to a wealthy stockbroker living the high life to his fall involving crime and corruption.",
        "rating": 8.2,
        "popularity": 93,
        "is_trending": 1
    },
    {
        "id": 18,
        "title": "Forrest Gump",
        "genre": "Drama, Romance",
        "director": "Robert Zemeckis",
        "cast": "Tom Hanks, Robin Wright, Gary Sinise",
        "year": 1994,
        "description": "The history of the United States from the 1950s to the 1970s unfolds from the perspective of an Alabama man with an IQ of 75.",
        "rating": 8.8,
        "popularity": 95,
        "is_trending": 0
    },
    {
        "id": 19,
        "title": "Saving Private Ryan",
        "genre": "Drama, War",
        "director": "Steven Spielberg",
        "cast": "Tom Hanks, Matt Damon, Tom Sizemore",
        "year": 1998,
        "description": "Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.",
        "rating": 8.6,
        "popularity": 93,
        "is_trending": 0
    },
    {
        "id": 20,
        "title": "Jurassic Park",
        "genre": "Adventure, Sci-Fi",
        "director": "Steven Spielberg",
        "cast": "Sam Neill, Laura Dern, Jeff Goldblum",
        "year": 1993,
        "description": "A pragmatic paleontologist visiting an almost complete theme park is tasked with protecting kids after a power failure causes cloned dinosaurs to run loose.",
        "rating": 8.2,
        "popularity": 90,
        "is_trending": 0
    },
    {
        "id": 21,
        "title": "Raiders of the Lost Ark",
        "genre": "Action, Adventure",
        "director": "Steven Spielberg",
        "cast": "Harrison Ford, Karen Allen, Paul Freeman",
        "year": 1981,
        "description": "In 1936, archaeologist and adventurer Indiana Jones is hired by the U.S. government to find the Ark of the Covenant before the Nazis can.",
        "rating": 8.4,
        "popularity": 89,
        "is_trending": 0
    },
    {
        "id": 22,
        "title": "Schindler's List",
        "genre": "Biography, Drama, History",
        "director": "Steven Spielberg",
        "cast": "Liam Neeson, Ralph Fiennes, Ben Kingsley",
        "year": 1993,
        "description": "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce.",
        "rating": 9.0,
        "popularity": 94,
        "is_trending": 0
    },
    {
        "id": 23,
        "title": "The Prestige",
        "genre": "Drama, Mystery, Sci-Fi",
        "director": "Christopher Nolan",
        "cast": "Hugh Jackman, Christian Bale, Scarlett Johansson",
        "year": 2006,
        "description": "After a tragic accident, two stage magicians in 1890s London engage in a battle to create the ultimate illusion.",
        "rating": 8.5,
        "popularity": 92,
        "is_trending": 0
    },
    {
        "id": 24,
        "title": "Memento",
        "genre": "Mystery, Thriller",
        "director": "Christopher Nolan",
        "cast": "Guy Pearce, Carrie-Anne Moss, Joe Pantoliano",
        "year": 2000,
        "description": "A man with short-term memory loss attempts to track down his wife's murderer using notes, photos, and tattoos.",
        "rating": 8.4,
        "popularity": 89,
        "is_trending": 0
    },
    {
        "id": 25,
        "title": "Whiplash",
        "genre": "Drama, Music",
        "director": "Damien Chazelle",
        "cast": "Miles Teller, J.K. Simmons, Paul Reiser",
        "year": 2014,
        "description": "A promising young drummer enrolls at a cut-throat music conservatory where his dreams are mentored by an abusive instructor.",
        "rating": 8.5,
        "popularity": 92,
        "is_trending": 0
    },
    {
        "id": 26,
        "title": "La La Land",
        "genre": "Comedy, Drama, Music, Romance",
        "director": "Damien Chazelle",
        "cast": "Ryan Gosling, Emma Stone, Rosemarie DeWitt",
        "year": 2016,
        "description": "While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations.",
        "rating": 8.0,
        "popularity": 89,
        "is_trending": 1
    },
    {
        "id": 27,
        "title": "Titanic",
        "genre": "Drama, Romance",
        "director": "James Cameron",
        "cast": "Leonardo DiCaprio, Kate Winslet, Billy Zane",
        "year": 1997,
        "description": "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.",
        "rating": 7.9,
        "popularity": 94,
        "is_trending": 0
    },
    {
        "id": 28,
        "title": "Avatar",
        "genre": "Action, Adventure, Fantasy, Sci-Fi",
        "director": "James Cameron",
        "cast": "Sam Worthington, Zoe Saldana, Sigourney Weaver",
        "year": 2009,
        "description": "A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between orders and protecting the alien world.",
        "rating": 7.9,
        "popularity": 91,
        "is_trending": 1
    },
    {
        "id": 29,
        "title": "Avatar: The Way of Water",
        "genre": "Action, Adventure, Fantasy, Sci-Fi",
        "director": "James Cameron",
        "cast": "Sam Worthington, Zoe Saldana, Sigourney Weaver",
        "year": 2022,
        "description": "Jake Sully lives with his family on Pandora. When a familiar threat returns, they must work together to protect their home.",
        "rating": 7.6,
        "popularity": 88,
        "is_trending": 1
    },
    {
        "id": 30,
        "title": "Gladiator",
        "genre": "Action, Adventure, Drama",
        "director": "Ridley Scott",
        "cast": "Russell Crowe, Joaquin Phoenix, Connie Nielsen",
        "year": 2000,
        "description": "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
        "rating": 8.5,
        "popularity": 93,
        "is_trending": 0
    },
    {
        "id": 31,
        "title": "Blade Runner",
        "genre": "Sci-Fi, Thriller",
        "director": "Ridley Scott",
        "cast": "Harrison Ford, Rutger Hauer, Sean Young",
        "year": 1982,
        "description": "A blade runner must pursue and terminate four replicants who stole a ship in space and have returned to Earth to find their creator.",
        "rating": 8.1,
        "popularity": 87,
        "is_trending": 0
    },
    {
        "id": 32,
        "title": "Alien",
        "genre": "Horror, Sci-Fi",
        "director": "Ridley Scott",
        "cast": "Sigourney Weaver, Tom Skerritt, John Hurt",
        "year": 1979,
        "description": "The crew of a commercial spacecraft encounter a deadly lifeform after investigating an unknown transmission on an alien planet.",
        "rating": 8.5,
        "popularity": 90,
        "is_trending": 0
    },
    {
        "id": 33,
        "title": "The Martian",
        "genre": "Adventure, Drama, Sci-Fi",
        "director": "Ridley Scott",
        "cast": "Matt Damon, Jessica Chastain, Kristen Wiig",
        "year": 2015,
        "description": "An astronaut becomes stranded on Mars after his crew assume him dead, and must rely on his ingenuity to find a way to signal to Earth.",
        "rating": 8.0,
        "popularity": 88,
        "is_trending": 1
    },
    {
        "id": 34,
        "title": "The Lord of the Rings: The Fellowship of the Ring",
        "genre": "Action, Adventure, Drama, Fantasy",
        "director": "Peter Jackson",
        "cast": "Elijah Wood, Ian McKellen, Orlando Bloom",
        "year": 2001,
        "description": "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth.",
        "rating": 8.9,
        "popularity": 96,
        "is_trending": 0
    },
    {
        "id": 35,
        "title": "The Lord of the Rings: The Two Towers",
        "genre": "Action, Adventure, Drama, Fantasy",
        "director": "Peter Jackson",
        "cast": "Elijah Wood, Ian McKellen, Viggo Mortensen",
        "year": 2002,
        "description": "While Frodo and Sam edge closer to Mordor, the divided fellowship makes a stand against Sauron's new ally Saruman.",
        "rating": 8.8,
        "popularity": 95,
        "is_trending": 0
    },
    {
        "id": 36,
        "title": "The Lord of the Rings: The Return of the King",
        "genre": "Action, Adventure, Drama, Fantasy",
        "director": "Peter Jackson",
        "cast": "Elijah Wood, Viggo Mortensen, Ian McKellen",
        "year": 2003,
        "description": "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam approaching Mount Doom.",
        "rating": 9.0,
        "popularity": 97,
        "is_trending": 1
    },
    {
        "id": 37,
        "title": "Spirited Away",
        "genre": "Animation, Adventure, Family, Fantasy",
        "director": "Hayao Miyazaki",
        "cast": "Daveigh Chase, Suzanne Pleshette, Jason Marsden",
        "year": 2001,
        "description": "During her family's move to the suburbs, a 10-year-old girl wanders into a world ruled by gods, witches, and spirits.",
        "rating": 8.6,
        "popularity": 92,
        "is_trending": 0
    },
    {
        "id": 38,
        "title": "Parasite",
        "genre": "Drama, Thriller",
        "director": "Bong Joon Ho",
        "cast": "Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong",
        "year": 2019,
        "description": "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
        "rating": 8.5,
        "popularity": 93,
        "is_trending": 1
    },
    {
        "id": 39,
        "title": "Get Out",
        "genre": "Horror, Mystery, Thriller",
        "director": "Jordan Peele",
        "cast": "Daniel Kaluuya, Allison Williams, Bradley Whitford",
        "year": 2017,
        "description": "A young African-American visits his white girlfriend's parents for the weekend, where his simmering uneasiness reaches a boiling point.",
        "rating": 7.8,
        "popularity": 87,
        "is_trending": 1
    },
    {
        "id": 40,
        "title": "Hereditary",
        "genre": "Horror, Drama, Mystery",
        "director": "Ari Aster",
        "cast": "Toni Collette, Milly Shapiro, Gabriel Byrne",
        "year": 2018,
        "description": "A grieving family is haunted by tragic and disturbing occurrences after the death of their secretive grandmother.",
        "rating": 7.3,
        "popularity": 83,
        "is_trending": 1
    },
    {
        "id": 41,
        "title": "The Conjuring",
        "genre": "Horror, Mystery, Thriller",
        "director": "James Wan",
        "cast": "Patrick Wilson, Vera Farmiga, Ron Livingston",
        "year": 2013,
        "description": "Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark, demonic presence in their farmhouse.",
        "rating": 7.5,
        "popularity": 86,
        "is_trending": 0
    },
    {
        "id": 42,
        "title": "A Quiet Place",
        "genre": "Horror, Sci-Fi, Drama",
        "director": "John Krasinski",
        "cast": "Emily Blunt, John Krasinski, Millicent Simmonds",
        "year": 2018,
        "description": "A family struggles for survival in a world where blind but noise-sensitive creatures have wiped out most of the human population.",
        "rating": 7.5,
        "popularity": 85,
        "is_trending": 1
    },
    {
        "id": 43,
        "title": "The Shining",
        "genre": "Horror, Drama",
        "director": "Stanley Kubrick",
        "cast": "Jack Nicholson, Shelley Duvall, Danny Lloyd",
        "year": 1980,
        "description": "A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence.",
        "rating": 8.4,
        "popularity": 91,
        "is_trending": 0
    },
    {
        "id": 44,
        "title": "Psycho",
        "genre": "Horror, Mystery, Thriller",
        "director": "Alfred Hitchcock",
        "cast": "Anthony Perkins, Janet Leigh, Vera Miles",
        "year": 1960,
        "description": "A secretary on the run checks into a remote motel run by a young man under the domination of his mother.",
        "rating": 8.5,
        "popularity": 89,
        "is_trending": 0
    },
    {
        "id": 45,
        "title": "Spider-Man: Into the Spider-Verse",
        "genre": "Animation, Action, Adventure, Sci-Fi",
        "director": "Bob Persichetti",
        "cast": "Shameik Moore, Jake Johnson, Hailee Steinfeld",
        "year": 2018,
        "description": "Teen Miles Morales becomes the Spider-Man of his universe, and joins with spider-powered heroes from other dimensions.",
        "rating": 8.4,
        "popularity": 93,
        "is_trending": 1
    },
    {
        "id": 46,
        "title": "Spider-Man: Across the Spider-Verse",
        "genre": "Animation, Action, Adventure, Sci-Fi",
        "director": "Joaquim Dos Santos",
        "cast": "Shameik Moore, Hailee Steinfeld, Oscar Isaac",
        "year": 2023,
        "description": "Miles Morales catapults across the Multiverse, clashing with a team of Spider-People charged with protecting its very existence.",
        "rating": 8.6,
        "popularity": 94,
        "is_trending": 1
    },
    {
        "id": 47,
        "title": "Toy Story",
        "genre": "Animation, Adventure, Comedy",
        "director": "John Lasseter",
        "cast": "Tom Hanks, Tim Allen, Don Rickles",
        "year": 1995,
        "description": "A cowboy doll is profoundly threatened and jealous when a new spaceman action figure supplants him as top toy in a boy's bedroom.",
        "rating": 8.3,
        "popularity": 90,
        "is_trending": 0
    },
    {
        "id": 48,
        "title": "Inside Out",
        "genre": "Animation, Adventure, Comedy, Drama",
        "director": "Pete Docter",
        "cast": "Amy Poehler, Bill Hader, Lewis Black",
        "year": 2015,
        "description": "After a young girl is uprooted from her life, her core emotions - Joy, Fear, Anger, Disgust and Sadness - conflict on how to navigate a new city.",
        "rating": 8.1,
        "popularity": 89,
        "is_trending": 0
    },
    {
        "id": 49,
        "title": "Coco",
        "genre": "Animation, Adventure, Comedy, Family, Fantasy",
        "director": "Lee Unkrich",
        "cast": "Anthony Gonzalez, Gael Garcia Bernal, Benjamin Bratt",
        "year": 2017,
        "description": "Aspiring musician Miguel enters the Land of the Dead to find his legendary singer great-great-grandfather.",
        "rating": 8.4,
        "popularity": 92,
        "is_trending": 1
    },
    {
        "id": 50,
        "title": "Your Name",
        "genre": "Animation, Drama, Fantasy, Romance",
        "director": "Makoto Shinkai",
        "cast": "Ryunosuke Kamiki, Mone Kamishiraishi, Ryo Narita",
        "year": 2016,
        "description": "Two high school strangers find themselves linked in a bizarre way, swapping bodies and searching for each other across space and time.",
        "rating": 8.4,
        "popularity": 91,
        "is_trending": 0
    },
    {
        "id": 51,
        "title": "Superbad",
        "genre": "Comedy",
        "director": "Greg Mottola",
        "cast": "Jonah Hill, Michael Cera, Christopher Mintz-Plasse",
        "year": 2007,
        "description": "Two co-dependent high school seniors are forced to deal with separation anxiety after their plan to stage a booze-fueled party goes awry.",
        "rating": 7.6,
        "popularity": 88,
        "is_trending": 0
    },
    {
        "id": 52,
        "title": "The Hangover",
        "genre": "Comedy",
        "director": "Todd Phillips",
        "cast": "Bradley Cooper, Ed Helms, Zach Galifianakis",
        "year": 2009,
        "description": "Three buddies wake up from a wild bachelor party in Las Vegas with no memory of the previous night and the groom missing.",
        "rating": 7.7,
        "popularity": 89,
        "is_trending": 0
    },
    {
        "id": 53,
        "title": "Groundhog Day",
        "genre": "Comedy, Fantasy, Romance",
        "director": "Harold Ramis",
        "cast": "Bill Murray, Andie MacDowell, Chris Elliott",
        "year": 1993,
        "description": "A narcissistic, self-centered weatherman finds himself inexplicably living the same day over and over again.",
        "rating": 8.0,
        "popularity": 88,
        "is_trending": 0
    },
    {
        "id": 54,
        "title": "Step Brothers",
        "genre": "Comedy",
        "director": "Adam McKay",
        "cast": "Will Ferrell, John C. Reilly, Mary Steenburgen",
        "year": 2008,
        "description": "Two middle-aged, good-for-nothing men living with their parents are forced to become roommates when their parents marry.",
        "rating": 6.9,
        "popularity": 85,
        "is_trending": 0
    },
    {
        "id": 55,
        "title": "Anchorman: The Legend of Ron Burgundy",
        "genre": "Comedy",
        "director": "Adam McKay",
        "cast": "Will Ferrell, Christina Applegate, Steve Carell",
        "year": 2004,
        "description": "Ron Burgundy is San Diego's top-rated newsman in the 1970s, but his status is threatened when an ambitious new female anchor arrives.",
        "rating": 7.1,
        "popularity": 84,
        "is_trending": 0
    },
    {
        "id": 56,
        "title": "Booksmart",
        "genre": "Comedy",
        "director": "Olivia Wilde",
        "cast": "Kaitlyn Dever, Beanie Feldstein, Jessica Williams",
        "year": 2019,
        "description": "On the eve of graduation, two academic superstars realize they should have worked less and try to cram four years of fun into one night.",
        "rating": 7.2,
        "popularity": 81,
        "is_trending": 1
    },
    {
        "id": 57,
        "title": "Knives Out",
        "genre": "Comedy, Drama, Mystery, Thriller",
        "director": "Rian Johnson",
        "cast": "Daniel Craig, Chris Evans, Ana de Armas",
        "year": 2019,
        "description": "A detective investigates the death of the patriarch of an eccentric, combative, and highly dysfunctional family.",
        "rating": 7.9,
        "popularity": 90,
        "is_trending": 1
    },
    {
        "id": 58,
        "title": "Glass Onion: A Knives Out Mystery",
        "genre": "Comedy, Drama, Mystery, Thriller",
        "director": "Rian Johnson",
        "cast": "Daniel Craig, Edward Norton, Janelle Monae",
        "year": 2022,
        "description": "Tech billionaire Miles Bron invites his friends for a getaway on his private Greek island, but detective Benoit Blanc is put on the case when someone dies.",
        "rating": 7.1,
        "popularity": 86,
        "is_trending": 1
    },
    {
        "id": 59,
        "title": "Harry Potter and the Sorcerer's Stone",
        "genre": "Adventure, Family, Fantasy",
        "director": "Chris Columbus",
        "cast": "Daniel Radcliffe, Rupert Grint, Emma Watson",
        "year": 2001,
        "description": "An orphaned boy enrolls in a school of wizardry, where he learns the truth about himself, his family, and the dark forces that haunt the magical world.",
        "rating": 7.6,
        "popularity": 91,
        "is_trending": 0
    },
    {
        "id": 60,
        "title": "The Chronicles of Narnia: The Lion the Witch and the Wardrobe",
        "genre": "Adventure, Family, Fantasy",
        "director": "Andrew Adamson",
        "cast": "Tilda Swinton, Georgie Henley, William Moseley",
        "year": 2005,
        "description": "Four siblings travel through a wardrobe to the land of Narnia and learn of their destiny to free it with the guidance of a mystical lion.",
        "rating": 6.9,
        "popularity": 82,
        "is_trending": 0
    },
    {
        "id": 61,
        "title": "Pan's Labyrinth",
        "genre": "Drama, Fantasy, War",
        "director": "Guillermo del Toro",
        "cast": "Ivana Baquero, Ariadna Gil, Sergi Lopez",
        "year": 2006,
        "description": "In the Falangist Spain of 1944, a young girl escapes into a dark, eerie, but captivating fantasy world ruled by a mysterious faun.",
        "rating": 8.2,
        "popularity": 89,
        "is_trending": 0
    },
    {
        "id": 62,
        "title": "The Shape of Water",
        "genre": "Drama, Fantasy, Romance",
        "director": "Guillermo del Toro",
        "cast": "Sally Hawkins, Octavia Spencer, Michael Shannon",
        "year": 2017,
        "description": "At a top-secret research facility in the 1960s, a lonely janitor forms a unique relationship with an amphibious creature held in captivity.",
        "rating": 7.3,
        "popularity": 83,
        "is_trending": 1
    },
    {
        "id": 63,
        "title": "The Notebook",
        "genre": "Drama, Romance",
        "director": "Nick Cassavetes",
        "cast": "Gena Rowlands, James Garner, Rachel McAdams",
        "year": 2004,
        "description": "A poor yet passionate young man falls in love with a rich young woman, but they are soon separated because of social differences.",
        "rating": 7.8,
        "popularity": 86,
        "is_trending": 0
    },
    {
        "id": 64,
        "title": "Before Sunrise",
        "genre": "Drama, Romance",
        "director": "Richard Linklater",
        "cast": "Ethan Hawke, Julie Delpy, Andrea Eckert",
        "year": 1995,
        "description": "A young man and woman meet on a train in Europe and spend one romantic evening together in Vienna knowing it will probably be their only night.",
        "rating": 8.1,
        "popularity": 87,
        "is_trending": 0
    },
    {
        "id": 65,
        "title": "Pride & Prejudice",
        "genre": "Drama, Romance",
        "director": "Joe Wright",
        "cast": "Keira Knightley, Matthew Macfadyen, Brenda Blethyn",
        "year": 2005,
        "description": "Sparks fly when spirited Elizabeth Bennet meets single, rich, and proud Mr. Darcy, but Darcy reluctantly finds himself falling in love.",
        "rating": 7.8,
        "popularity": 88,
        "is_trending": 1
    },
    {
        "id": 66,
        "title": "About Time",
        "genre": "Comedy, Drama, Fantasy, Romance",
        "director": "Richard Curtis",
        "cast": "Domhnall Gleeson, Rachel McAdams, Bill Nighy",
        "year": 2013,
        "description": "At the age of 21, Tim discovers he can travel in time and change what happens in his own life to win the heart of a girl.",
        "rating": 7.8,
        "popularity": 87,
        "is_trending": 1
    },
    {
        "id": 67,
        "title": "Gone Girl",
        "genre": "Drama, Mystery, Thriller",
        "director": "David Fincher",
        "cast": "Ben Affleck, Rosamund Pike, Neil Patrick Harris",
        "year": 2014,
        "description": "With his wife's disappearance becoming a media circus, a husband sees the spotlight turned on him as he is suspected of foul play.",
        "rating": 8.1,
        "popularity": 89,
        "is_trending": 1
    },
    {
        "id": 68,
        "title": "Zodiac",
        "genre": "Crime, Drama, Mystery",
        "director": "David Fincher",
        "cast": "Jake Gyllenhaal, Robert Downey Jr., Mark Ruffalo",
        "year": 2007,
        "description": "In the late 1960s, a San Francisco cartoonist becomes obsessed with tracking down the Zodiac Killer who is terrorizing California.",
        "rating": 7.7,
        "popularity": 86,
        "is_trending": 0
    },
    {
        "id": 69,
        "title": "Prisoners",
        "genre": "Crime, Drama, Mystery, Thriller",
        "director": "Denis Villeneuve",
        "cast": "Hugh Jackman, Jake Gyllenhaal, Viola Davis",
        "year": 2013,
        "description": "When Keller Dover's daughter and her friend go missing, he takes matters into his own hands while the police pursue multiple leads.",
        "rating": 8.1,
        "popularity": 90,
        "is_trending": 1
    },
    {
        "id": 70,
        "title": "The Silence of the Lambs",
        "genre": "Crime, Drama, Thriller",
        "director": "Jonathan Demme",
        "cast": "Jodie Foster, Anthony Hopkins, Kasi Lemmons",
        "year": 1991,
        "description": "A young FBI cadet must receive the help of an incarcerated and manipulative cannibal killer to catch another serial killer.",
        "rating": 8.6,
        "popularity": 93,
        "is_trending": 0
    },
    {
        "id": 71,
        "title": "Heat",
        "genre": "Action, Crime, Drama",
        "director": "Michael Mann",
        "cast": "Al Pacino, Robert De Niro, Val Kilmer",
        "year": 1995,
        "description": "A group of high-end professional thieves start to feel the heat from the LAPD when they leave a clue at their latest heist.",
        "rating": 8.3,
        "popularity": 89,
        "is_trending": 0
    },
    {
        "id": 72,
        "title": "Mad Max: Fury Road",
        "genre": "Action, Adventure, Sci-Fi",
        "director": "George Miller",
        "cast": "Tom Hardy, Charlize Theron, Nicholas Hoult",
        "year": 2015,
        "description": "In a post-apocalyptic wasteland, a rebel woman and a drifter Max flee from a tyrannical ruler in a search for her homeland.",
        "rating": 8.1,
        "popularity": 91,
        "is_trending": 1
    },
    {
        "id": 73,
        "title": "Die Hard",
        "genre": "Action, Thriller",
        "director": "John McTiernan",
        "cast": "Bruce Willis, Alan Rickman, Bonnie Bedelia",
        "year": 1988,
        "description": "A New York City police officer tries to save his estranged wife and hostages taken by terrorists during a Christmas party in a Los Angeles skyscraper.",
        "rating": 8.2,
        "popularity": 88,
        "is_trending": 0
    },
    {
        "id": 74,
        "title": "John Wick",
        "genre": "Action, Thriller",
        "director": "Chad Stahelski",
        "cast": "Keanu Reeves, Michael Nyqvist, Alfie Allen",
        "year": 2014,
        "description": "An ex-hitman comes out of retirement to track down the gangsters that killed his dog and took everything from him.",
        "rating": 7.4,
        "popularity": 89,
        "is_trending": 1
    },
    {
        "id": 75,
        "title": "Gladiator II",
        "genre": "Action, Adventure, Drama",
        "director": "Ridley Scott",
        "cast": "Paul Mescal, Pedro Pascal, Connie Nielsen",
        "year": 2024,
        "description": "Years after witnessing the death of Maximus, Lucius enters the Colosseum to fight against tyrannical emperors leading Rome.",
        "rating": 6.8,
        "popularity": 85,
        "is_trending": 1
    }
]

df = pd.DataFrame(movies)
df.to_csv("data/movies.csv", index=False)
print("movies.csv written successfully with proper quotes!")
